export const TAG_COUNTERS: Record<string, Record<string, number>> = {
  mana_drain: { mana_dependent: 2.0, medusa: 2.5, caster: 1.5 },
  mana_burn: { mana_dependent: 2.0, medusa: 2.5, caster: 1.5 },
  break: { passive_tank: 2.0, bristleback: 2.5, evasion: 1.5, durable: 1.2, tuff: 1.2 },
  anti_heal: { high_regen: 2.0, healing: 1.5, tank: 1.2, sustain: 1.5, lifesteal: 1.5, huskar: 2.0, alchemist: 2.0 },
  true_sight: { invisibility: 2.0, escape: 1.2, juke: 1.2, riki: 2.0, bounty_hunter: 1.5, templar_assassin: 1.5 },
  armor: { physical_damage: 1.5, carry: 1.2, agility_core: 1.2, burst: 1.2, armor_corruption: 1.5 },
  magic_resistance: { magic_damage: 1.5, nuker: 1.5, aoe_magic: 1.5, burst: 1.2, zeus: 2.0 },
  ethereal: { physical_damage: 2.0, carry: 1.5, agility_core: 1.5, ursa: 2.0, phantom_assassin: 2.0 },
  silence: { escape: 1.8, caster: 1.8, mana_dependent: 1.5, mobility: 1.5, storm_spirit: 2.0, puck: 2.0 },
  dispel: { buff: 1.5, save: 1.5, ethereal: 1.5, physical_shield: 1.5, omniknight: 2.0 },
  continuous_dispel: { buff: 2.0, save: 2.0, ethereal: 2.0, physical_shield: 2.0, omniknight: 2.5 },
  true_strike: { evasion: 2.5, phantom_assassin: 2.5, windranger: 2.0 },
  armor_corruption: { durable: 1.5, tank: 1.5, tuff: 1.5, armor: 1.8 },
  damage_reflection: { nuker: 1.5, carry: 1.5, burst: 1.8, glass_cannon: 2.0, aoe_damage: 1.2 },
  spell_immunity: { disabler: 1.8, nuker: 1.5, magical: 1.5, mana_burn: 1.2, magic_damage: 1.5, aoe_magic: 1.5 },
  evasion: { physical_damage: 1.5, carry: 1.5, agility_core: 1.5 },
  aoe_damage: { illusioner: 2.0, pusher: 1.5, summoning: 1.5, phantom_lancer: 2.0, naga_siren: 2.0, meepo: 2.0, broodmother: 2.0 },
  aoe_magic: { pusher: 1.5, summoning: 1.5, meepo: 1.5 },
  cleave: { illusioner: 3.0, phantom_lancer: 3.0, naga_siren: 2.5, chaos_knight: 2.5, broodmother: 2.5, meepo: 2.0, summoning: 2.0 },
  hard_control: { escape: 2.5, mobility: 2.0, carry: 1.5, storm_spirit: 3.0, weaver: 2.5, anti_mage: 2.5, puck: 2.5 },
  disabler: { carry: 1.5, brawler: 1.2 },
  root: { mobility: 2.5, escape: 2.0, storm_spirit: 3.0, weaver: 2.5, anti_mage: 2.0, puck: 2.0, lycan: 2.5, bloodseeker: 2.0 },
  disarm: { physical_damage: 2.0, carry: 1.8, agility_core: 1.5, attack_speed: 1.5, ursa: 2.0, troll_warlord: 2.0 },
  spell_block: { single_target_spell: 2.0, catch: 1.5, initiator: 1.2, doom: 2.0, legion_commander: 2.0 },
  pure_damage: { tank: 1.8, durable: 1.5, tuff: 1.5, armor: 2.0, magic_resistance: 2.0 },
  anti_illusion: { illusioner: 2.5, phantom_lancer: 2.5, naga_siren: 2.0, chaos_knight: 1.8 },
  anti_tank: { tank: 2.0, durable: 1.8, tuff: 1.8 },
  burst: { squishy_support: 2.0, squishy_early: 1.8, escape: 1.5, glass_cannon: 2.0 },
  catch: { escape: 1.8, mobility: 1.5, sniper: 2.0, drow_ranger: 2.0 },
  illusioner: { single_target_spell: 2.0, lack_aoe: 2.0 },
  summoning: { single_target_spell: 1.5, lack_aoe: 1.8 },
  anti_magic: { nuker: 1.8, magic_damage: 2.0, caster: 1.5 },
  anti_melee: { melee: 1.5, brawler: 1.5 },
  save: { burst: 1.5, hard_control: 1.5, catch: 1.5, initiator: 1.2 },
  hard_save: { burst: 2.0, hard_control: 2.0, catch: 2.0, initiator: 1.8 },
  anti_save: { save: 2.0, hard_save: 2.0, dazzle: 2.0, oracle: 2.0, omniknight: 2.0 },
};

export const TAG_SYNERGIES: Record<string, Record<string, number>> = {
  healing: { tank: 1.5, durable: 1.5, tuff: 1.5, squishy_early: 1.2 },
  initiator: { aoe_damage: 1.8, nuker: 1.5, teamfight: 1.5, catch: 1.2 },
  aoe_stun: { aoe_magic: 2.0, aoe_damage: 2.0, teamfight: 1.8 },
  disabler: { carry: 1.5, physical_damage: 1.5, burst: 1.5, glass_cannon: 1.5 },
  mana_restore: { mana_dependent: 2.0, caster: 1.8, nuker: 1.2 },
  save: { carry: 1.5, squishy_early: 1.8, glass_cannon: 2.0, hard_carry: 1.8 },
  hard_save: { carry: 1.8, squishy_early: 2.0, glass_cannon: 2.5, hard_carry: 2.0 },
  buff: { carry: 1.5, agility_core: 1.5, physical_damage: 1.5 },
  aura_movement: { teamfight: 1.5, catch: 1.5, mobility: 1.2 },
  aura_attack_speed: { carry: 1.5, physical_damage: 1.5, pushing: 1.5 },
  aura_armor: { teamfight: 1.5, pushing: 1.5, squishy_support: 1.5 },
  armor_corruption: { physical_damage: 1.8, carry: 1.5, burst: 1.5 },
  magic_corruption: { magic_damage: 1.8, nuker: 1.5, caster: 1.5 },
  spell_amp: { nuker: 1.8, caster: 1.8, magic_damage: 1.8 },
  lifesteal: { brawler: 1.5, durable: 1.2, carry: 1.2 },
  spell_lifesteal: { nuker: 1.8, caster: 1.5, durable_caster: 2.0, leshrac: 2.0, bristleback: 2.0 },
  mobility: { initiator: 1.5, escape: 1.5, catch: 1.5 },
  global_mobility: { carry: 1.5, pusher: 1.5, global_presence: 1.5 },
  attack_speed: { damage_proc: 1.8, bash: 1.8, carry: 1.2 },
};
